### ISSUE TITLE
Populate Voters field on results page

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#10]
As a user, 
I'd like to know the number of voters who contributed to a ballot,
So that I may get a sense of if it was one person using all their votes or many people using little amounts. 

Technical Details:
The poll manager contract will need to be updated with a voters increment in the vote function. This may increase GAS costs. 

![voting dapp experience 6](https://user-images.githubusercontent.com/7915365/47495094-33eb3700-d84b-11e8-863c-f4fe5f46f0a8.jpg)

**Comment by richard-ramos** [comment]
Pushed fix on `new-ui` branch.
