### ISSUE TITLE
Randomize Ballots in UI (WIP)

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#12]
As a user, 
when arriving at the vote page,
the order of the ballots will be different to a user who visits the dapp after me. 

Details: 
Randomizing the order of votes becomes important when the list of ballots grows in length to prevent order bais. 

https://www.surveymonkey.com/curiosity/eliminate-order-bias-to-improve-your-survey-responses/

**Comment by richard-ramos** [comment]
Code already implemented. But commented due to this being a WIP
