### ISSUE TITLE
Chevron on results is not tappable

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#13]
Currently, on transaction pending and results page the user needs to tap on the voting results in order to display the ballot information. 

The desired behavior is that the user could tap on the results bar or the chevron to display or hide the voting information. 

<img width="405" alt="screen shot 2018-10-25 at 11 38 46" src="https://user-images.githubusercontent.com/7915365/47496698-89c1de00-d84f-11e8-823c-d2036d19dcdb.png">

**Comment by richard-ramos** [comment]
Fix pushed to `new-ui` branch
