### ISSUE TITLE
Copy change: "connect your wallet" should say "next" 

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#20]
Because the flow changed, if a web 3 connection is detected, the user goes straight from "how voting works" to "voting credits". 

<img width="378" alt="screen shot 2018-10-28 at 20 40 10" src="https://user-images.githubusercontent.com/7915365/47621567-b8f77a00-daf1-11e8-8d35-75232e41d39a.png">
Please change "connect your wallet" to "next".

**Comment by richard-ramos** [comment]
Fix pushed to `new-ui` branch.
New URL: https://ipfs.infura.io/ipfs/QmP2BKTQFrkzDsWC32KVXmPVGe7TxSLmP1jg4nMmZisvs9/
