### ISSUE TITLE
Add a loading animation to "transaction in process" icon. 

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#21]
As a user, 
I want an indicator to visually show me my transaction is been processed,
So that I wait on the page for my transaction to be completed. 

<img width="364" alt="screen shot 2018-10-28 at 20 44 58" src="https://user-images.githubusercontent.com/7915365/47621616-5fdc1600-daf2-11e8-8b43-3cf2963f46e7.png">

**Comment by Graeme-Code** [comment]
Asked Euge to create a GIF.

**Comment by EugeOrtiz** [comment]
Here is the code [https://codepen.io/anon/pen/YJMVvN](https://codepen.io/anon/pen/YJMVvN )

**Comment by EugeOrtiz** [comment]
[Rounded version](https://codepen.io/anon/pen/MPRqyp) (raw code)

**Comment by richard-ramos** [comment]
Ropsten:
https://ipfs.infura.io/ipfs/QmWeTyeSsuQCZ9q6e6MY9fVyeepooMf888QqiEQ3P9TLzG/

**Comment by Graeme-Code** [comment]
confirm this is working. closing.
