### ISSUE TITLE
Long title go past chevon on mobile devices

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#22]
As I user, 
I don' t want to see the title go past the chevon,
So that the chevon is clearly tappable. 

As I user,
If I expand the results, I should see the title text which was cut off,
So that I can investigate the complete title. 

Illustration of issue
![unnamed](https://user-images.githubusercontent.com/7915365/47621757-5489ea00-daf4-11e8-8f56-36cba2dfd18e.jpg)

Design required

**Comment by EugeOrtiz** [comment]
See designs [here](https://www.figma.com/file/L1qhHMiZr5dTVdDxrjsbxHYp/Voting-Dapp?node-id=306%3A0) (Figma).

![congrats -_ list 2 lines](https://user-images.githubusercontent.com/37297779/47650026-446b1c80-db7f-11e8-850f-86bd68022fdb.png)

**Comment by richard-ramos** [comment]
The behaviour when scrolling the results will be applied as part of #27 #28

**Comment by asemiankevich** [comment]
looks nice on Ropsten
![image](https://user-images.githubusercontent.com/28752642/48137343-e2af5e80-e2b2-11e8-99e5-cbbe7cff6dc0.png)
