### ISSUE TITLE
Footer covers "get started" button

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#23]
On Android devices, the footer covers the "get started" button. Please unpin the footer on the landing page so that an android user may scroll down to see the get started button.

**Comment by richard-ramos** [comment]
Fix pushed to `new-ui` branch.
New URL: https://ipfs.infura.io/ipfs/QmP2BKTQFrkzDsWC32KVXmPVGe7TxSLmP1jg4nMmZisvs9/
