### ISSUE TITLE
CTA's are too small

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/snt-voting#25]
## Description
Fixed CTAs are not noticeable enough since the fonts are too small:

![img_7520](https://user-images.githubusercontent.com/37297779/49017988-ed01a180-f168-11e8-9860-3ae55c345b8b.PNG)

## Expected results
CTA's font size should be Regular / 15px / line-height: 22px;
![step2 -_ options](https://user-images.githubusercontent.com/37297779/49018076-3651f100-f169-11e8-8573-7e23ee8ee1a7.png)

[Designs on Figma](https://www.figma.com/file/L1qhHMiZr5dTVdDxrjsbxHYp/Voting-Dapp?node-id=314%3A77)

**Comment by anshumanv** [comment]
Hey @richard-ramos is this fixed yet? If not I'll be able to fix this. 😄

**Comment by richard-ramos** [comment]
Yes, it seems to have been fixed with one of the css related bounties! :)
![screenshot from 2019-01-17 11-58-15](https://user-images.githubusercontent.com/1106587/51331125-602fe180-1a4f-11e9-8244-ba94a4ad94b5.png)
