### ISSUE TITLE
Permission to the dapp is not asked when Opt In web3 toggle is enabled

### ISSUE THREAD

**Issue by asemiankevich** [status-im/snt-voting#29]
Expected:

![image](https://user-images.githubusercontent.com/28752642/47703655-02e77980-dc32-11e8-84a0-76c73c259619.png)

Actual: no permission window is shown when Web3 Opt In toggle is enabled

Steps:
- open status
- switch to ropsten
- profile -> advanced -> dev mode -> web3 Opt In -> On
- open https://ipfs.infura.io/ipfs/QmXj4bGUudifqw24EFeXXYEesEdvunj9pxG89pcmUNgpBw/#/ in status browser

**Comment by Graeme-Code** [comment]
linking to #30

**Comment by richard-ramos** [comment]
Ropsten:
https://ipfs.infura.io/ipfs/Qme2JNFgGLZrg5CfjkiAM1GeHD2dzKKc1KkASqkhnD9H5C
