### ISSUE TITLE
Status is not detected automatically in Voting dapp when Web3 Opt In is enabled

### ISSUE THREAD

**Issue by asemiankevich** [status-im/snt-voting#30]
Actual:
![image](https://user-images.githubusercontent.com/28752642/47703931-ed268400-dc32-11e8-9044-53cd6fccff3d.png)

When i tap `CONNECT WITH STATUS` it redirects me to the link `Open in status`.

Expected: Status is  detected automatically so I dont need to do anything else to proceed.

@richard-ramos @Graeme-Code

**Comment by lukaszfryc** [comment]
@richard-ramos I have the same when **web3 is disabled** and I go back to previous page. E.g. I'm on  "How it works" and go back to first page.

**Comment by Graeme-Code** [comment]
Linked this to note in a project board. Richard is working with Dapp team and Luri from embark to resolve.

**Comment by richard-ramos** [comment]
Ropsten:
https://ipfs.infura.io/ipfs/Qme2JNFgGLZrg5CfjkiAM1GeHD2dzKKc1KkASqkhnD9H5C

**Comment by richard-ramos** [comment]
So, a note here
The latest fix added to Embark adds support for EIP1102, however, it has the inconvenient that it will ask for permission to access to the wallet in the first screen rather where it should be according to the proposed design.. 

This issue will need to be revisited in the future.
