### ISSUE TITLE
No prompt when you are on wrong network

### ISSUE THREAD

**Issue by churik** [status-im/snt-voting#31]
When you are on Mainnet, but DApp is running only on Ropsten network, no readable error for user is shown

**Steps:**
- change your MetaMask or Status to MainNet
- go to the one of test contract, i.e. `https://ipfs.infura.io/ipfs/QmXj4bGUudifqw24EFeXXYEesEdvunj9pxG89pcmUNgpBw/`

**Expected result:**
DApp can prompt user to switch network
**Actual result:**
Error in console:
```
Uncaught (in promise) Error: Returned values aren't valid, did it run Out of Gas?
    at s.decodeParameters (dapp.js:58)
    at k.d._decodeMethodReturn (dapp.js:58)
    at c.outputFormatter (dapp.js:58)
    at c.formatOutput (dapp.js:42)
    at o (dapp.js:42)
    at dapp.js:96
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1
```

**Comment by richard-ramos** [comment]
Fix pushed to `new-ui` branch.
https://ipfs.infura.io/ipfs/QmawA3Gy76PsTScBCWaXFP36szLzGzXKRPQFxFsdYgZS3a/#/

**Comment by churik** [comment]
Checked on MetaMask (desktop) and in Status(mobile)
