### ISSUE TITLE
Transaction is confirmed is shown when txn is not actually confirmed

### ISSUE THREAD

**Issue by asemiankevich** [status-im/snt-voting#33]
So the issue is the following:

1. user sees the green confirmation screen of the txn but the txn is not confirmed
2. the poll results are not updated (because the txn is not confirmed). It is especially scary when you are the first one completing the poll and see all zeroes
3. link to transaction shows that transaction is not found (shows MAINNET links while on Ropsten)
4. when i tap this etherscan link and then tap back - the green confirmation for the transaction disappears
5. page is not refreshed automatically

![image](https://user-images.githubusercontent.com/28752642/47707432-d7b65780-dc3c-11e8-99a0-ea52750c9772.png)

![image](https://user-images.githubusercontent.com/28752642/47707509-10563100-dc3d-11e8-8389-5ab6c1356d40.png)

@richard-ramos @Graeme-Code

**Comment by Graeme-Code** [comment]
Putting this in progress Q.

**Comment by asemiankevich** [comment]
@richard-ramos awesome work!! Looks very user-friendly now! Just wanna ask - did we intentionally removed this `view on etherscan` link?

**Comment by richard-ramos** [comment]
@asemiankevich Fixed the etherscan link issue!
https://ipfs.infura.io/ipfs/QmPybbteCPNPwTQ2z6ba4X2Rhpy4zCxbqPBu866FaPQjrp/

**Comment by asemiankevich** [comment]
@richard-ramos can we make it opening in new window? like it was before. This back navigation is really painful in this case

**Comment by richard-ramos** [comment]
@asemiankevich 
https://ipfs.infura.io/ipfs/QmNnzWGhqA6UUzc2VLNPnWFGQafJJTx5qxDwP8bxRhTRrP/#/

**Comment by asemiankevich** [comment]
well this link still opens in same window ( app does not ask me how to open it anyway). besides that it is much better than it was. Lets close it and see how it goes

**Comment by richard-ramos** [comment]
yeah. Seems like the Status app does not handle multiple windows/tabs. Would be a cool feature to have!
