### ISSUE TITLE
Need help footer is not shown

### ISSUE THREAD

**Issue by asemiankevich** [status-im/snt-voting#34]
Expected:

![image](https://user-images.githubusercontent.com/28752642/47708616-8065b680-dc3f-11e8-9cb4-60501e04dcda.png)

Actual:

![image](https://user-images.githubusercontent.com/28752642/47708597-76dc4e80-dc3f-11e8-8152-4e8146a3f581.png)

**Comment by Graeme-Code** [comment]
This has yet to be implemented. Issue is https://github.com/status-im/snt-voting/issues/6
