### ISSUE TITLE
Redirection to the poll from a browser page needs to be updated

### ISSUE THREAD

**Issue by SlizkovaGanna** [status-im/snt-voting#37]
When you are opening a link to the poll from your browser, 'Open in Status' button leads to an invalid URL

**Steps:**
1. Open a link to your poll in browser 
2. Select 'Connect using Status' button
3. In a Browse pop-up, select 'Open in Status'

**Expected result:**
You are redirected to your poll's URL

**Actual result:**
For Android: vote.status.im page is stuck loading
For iOS: an outdated page with the previous poll is stuck loading

**Comment by Graeme-Code** [comment]
Added this issue to resolve issue :https://github.com/status-im/snt-voting/issues/38
