### ISSUE TITLE
If status browser, if no web3 provider detected, add delay and retry. 

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#38]
User of status who has a slow connection has been experiencing a bug. Essentailly when hitting vote.status.im they encounter a ERROR, Incorrect URL scheme. 

After discussion with Dapp team the response for this is redirect combined with status browser not being able to inject web3. 

The proposed solution is that if the dapp detects no web3 connection when user is in status browser, to run a delay and check again for web 3 connection. 

The optimum time for the delay is not determined. Recommend adding 5 seconds and check from there.

**Comment by Graeme-Code** [comment]
Linked to issue https://github.com/status-im/snt-voting/issues/37

**Comment by Graeme-Code** [comment]
and issue #30

**Comment by Serhy** [comment]
Has been tested on 2G + poor VPN enabled on Android 7 and iOS. Page load delayed for ~20-25 seconds but eventually content appeared in Status browser fine.

**Comment by bgits** [comment]
Just seeing this. Ideally this should be a general component as it's not only a problem that will be experienced in the voting dapp.
