### ISSUE TITLE
"Chat with us" links on Status browser doesn't redirect anywhere

### ISSUE THREAD

**Issue by churik** [status-im/snt-voting#39]
When you are on Mainnet, but DApp is running only on Ropsten network, no readable error for user is shown

**Steps:**
- open https://ipfs.infura.io/ipfs/QmYAVxjtbQBHD3ddgeLzFeGY8PqbThCMypw98w5QQeRxZR/
- pass "Get Started" > How voting Works > Next
- Tap on "Chat with us"

**Expected result:**
links are clickable ("Chat on Status", "Chat on Telegram", "Chat on Riot", "Faqs")
**Actual result:**
Nothing happens
<img width="419" alt="12345" src="https://user-images.githubusercontent.com/4557972/47850396-55ad6680-ddd5-11e8-9038-fec38d65bd20.png">

**Comment by richard-ramos** [comment]
Changed this dialog according to latest comments on #6

**Comment by Graeme-Code** [comment]
I'm closing this as its a duplication of #6
