### ISSUE TITLE
Landing Page with open, closed and create option

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#41]
User with ETH and SNT. 

As a user visiting the voting dapp, 
If my wallet is not connected I should see instructions to connect a wallet,
So that I may use the dapp. 

As a user on the landing page,
I should be able to view the most recent open and closed poll. 

<img width="150" alt="landing page" src="https://user-images.githubusercontent.com/7915365/48917744-58552600-ee80-11e8-8760-920ba6472478.png">

As a user,
I can tap “more open/closed polls” which displays (X) more polls,
So that I can view more polls which I could inspect further. 

The X is proportional to the amount of time taken to load additional polls. I feel 3 is a good number, but important that the wait is as short as possible. 

SNT/ETH management

As a user without ETH or SNT,
I should be informed of my need for SNT or ETH and unable to create a poll,
So that I dont find this out right before publishing a poll. 
![voting dapp experience 10](https://user-images.githubusercontent.com/7915365/48918031-e1209180-ee81-11e8-9f80-51dc7284aa1a.jpg)

**Comment by richard-ramos** [comment]
Code available in:
https://github.com/status-im/snt-voting/tree/landing-page

Create-Button is handled as part of #42

**Comment by richard-ramos** [comment]
Ropsten demo:
https://ipfs.infura.io/ipfs/QmaGSZUHUX2LWFNyk96pkmGYMkRkiTL3R7zoa33moktB1Z/#/

**Comment by Graeme-Code** [comment]
@richard-ramos Modification requested. Could the closed polls show the date they closed as per screenshot? 
<img width="338" alt="screen shot 2018-12-03 at 14 11 00" src="https://user-images.githubusercontent.com/7915365/49378873-a7fbe300-f705-11e8-921a-9a282452ac71.png">

**Comment by Graeme-Code** [comment]
Whooo!
