### ISSUE TITLE
Error screen is shown for a moment before starting the flow

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/snt-voting#49]
Type: Bug

## Problem
When tapping on "Create poll" icon, the SNT/ETH=0 error screen is shown for a moment. After that, the first step of the flow is shown.

![](https://im.ezgif.com/tmp/ezgif-1-6c48a2cb89f2.gif)

## Expected results
If there are no issues with ETH/SNT, the user shouldn't see the error screen.

## Steps to reproduce
1. Enter[ Org landing page](https://ipfs.io/ipfs/QmVkmZ465JVGpBtjuT5Gd5iaUvQgMxBfzXFyEqTQcPmgqS/#/) on Ropsten
2. Tap on "Create poll" icon (top right)
3. See screen

**Comment by richard-ramos** [comment]
@EugeOrtiz 
Please verify on this version: 
https://ipfs.infura.io/ipfs/QmQfUEi9GfVrWrZh11vGB4pNmjzLMibc7Un3X1trfyfmu3/#/
