### ISSUE TITLE
Options in list are draggable but they move when trying to scroll up/down

### ISSUE THREAD

**Issue by EugeOrtiz** [status-im/snt-voting#52]
## Problem
In step 3 (Add options) options are draggable (to reorder them) but when I want to scroll, the drag feature is activated (since I'm pressing on the screen to scroll). This makes scroll -to see the options- hard to use.

Example (trying to scroll up/down):

![](https://im5.ezgif.com/tmp/ezgif-5-51bdbdb37496.gif)

## Expected results
Draggable feature not interfering with scroll (enable drag and drop on long-press? remove it? ) 

This was found emulating a mobile device in Chrome browser. Needs to be checked on a mobile device.
@richard-ramos Can you help me reproduce this?

## Steps to reproduce

1. Initiate creation flow
2. In step 3 (add options) add several options to make a relative long list
3. Try to scroll up/down

**Comment by richard-ramos** [comment]
Indeed. The issue happens in mobile as well.
I'll attempt to disable the page scroll while an item is being dragged

**Comment by Graeme-Code** [comment]
I can confirm this problem is solved on mobile. Closing issue.
