### ISSUE TITLE
How Voting Works Text aligned to symbol

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#7]
When I view the "How Voting Works" page on mobile devices the text should not wrap to the edge of text container but stay in line with the symbol. 

![voting dapp experience 3](https://user-images.githubusercontent.com/7915365/47493585-87f41c80-d847-11e8-9d88-a25922382b30.jpg)

**Comment by richard-ramos** [comment]
Fix pushed to `new-ui` branch
