### ISSUE TITLE
Voting Credits/SNT/ETH count should be inline with label

### ISSUE THREAD

**Issue by Graeme-Code** [status-im/snt-voting#8]
On the voting credits page, the voting credits, SNT and ETH count should be in line with the label. Current the counter is in line with the text in line with the ! symbol. 

![voting dapp experience 4](https://user-images.githubusercontent.com/7915365/47493875-444de280-d848-11e8-81e2-df80a5edb6c0.jpg)

**Comment by richard-ramos** [comment]
Fixed
